### ISSUE TITLE
Event Tracking in Google Analytics - some PG pages being missed

### ISSUE THREAD

**Issue by STC21-UniKent** [unikent/of-course#632]
At present the event tracking is taken off on this page eg: http://www.kent.ac.uk/courses/postgraduate/apply-online/309 when the user clicks the button at the bottom of the page.

However there are many courses where this page is not used as the user is sent straight to the enquiry form eg Business Analytics http://www.kent.ac.uk/courses/postgraduate/292/business-analytics this is at PG level.

Therefore I don’t think we are tracking any metrics in Analytics on who has applied for these courses?

Is it possible to move the event tracking back to the courses pages themselves as was previously the case?

Many thanks

Sam

**Comment by aw285-unikent** [comment]
@STC21-UniKent HI Sam, please can you review this following your discussions on analytics this week and I could ask for it to go into BAU next week.

**Comment by eg270-unikent** [comment]
Hi @STC21-UniKent can you let me know what would be most useful to have in the apply link tracking on the course page? For the enquire link:
_pat.event('course-page', 'enquire-pg', '[Programme ID in Year] Course Title - full-time/part-time [MCR code]');

As the user will select the apply link before selecting mode of study (full-time/part-time) do you just want me to omit that and change the event to apply-pg? Or is there other information that would be useful for you to have?

**Comment by STC21-UniKent** [comment]
Hi @eg270-unikent Thinking about this is it possible to just add in event tracking code for the courses that don't have the middle page such as http://www.kent.ac.uk/courses/postgraduate/apply-online/309 ? 

I don't think it's worth moving all the tracking back to the apply link on the courses pages as it works ok as it is at present, it's just the courses which don't have the middle page that are an issue.

Having event action as 'apply-PG' and omitting the fulltime/part time would be fine for those particular courses (the ones that don't have the middle page) in the labeling.

Hope that makes sense, just shout if not.

**Comment by eg270-unikent** [comment]
Hi @STC21-UniKent I'm afraid we have no way of doing this in the codebase as the apply link goes to the apply-online page and it is only after clicking on this link that we determine whether the interim page should show or if the user should be taken straight to e:vision.

You will still get full-time or part-time in the event tracking on the interim page, so any events with the mode of study included will be from the interim page.

Alternatively we could rename the event tracking on the apply link on the course page and the next button on the interim page so that it's easier to distinguish between these. I'm not sure whether this would have a negative effect on the stats collected to date though.

**Comment by STC21-UniKent** [comment]
Hi @eg270-unikent Ok no problem thanks for letting me know, if we will still get the full/part time data for the appropriate courses then that's fine, for those that don;t have the option it's fine to omit in the labeling. 

Is that ok?
