### ISSUE TITLE
Allow preview of 2016 UG programmes on front-end

### ISSUE THREAD

**Issue by eg270-unikent** [unikent/of-course#674]
As EMS,

I want to be able to preview the web view of the 2016 UG Programmes

so that we can see how the programmes will look once published

- [ ] put at /courses/undergraduate/2016
- [ ] .htaccess so only staff can view

**Comment by cs462-unikent** [comment]
In order for previewing to work, i think a 2016 overridables & immutables need to be populated & published before hand.

https://webtools.kent.ac.uk/programmes/2016/ug/programmesettings/edit
https://webtools.kent.ac.uk/programmes/2016/globalsettings/edit

That said, i suspect we should capture the exception thrown by the preview button when this is not the case and provide a more helpful error message (rather than an empty PP screen)

**Comment by aw285-unikent** [comment]
@cs462-unikent shall I populate these?

**Comment by cs462-unikent** [comment]
Hello,

Yep, if possible that would be great. Once done the preview function should begin working.
I've additionally put in a pull request that should mean in future, it'll show an error if a preview cannot be generated for these reasons, rather than just a blank page. https://github.com/unikent/programmes-plant/pull/823

**Comment by eg270-unikent** [comment]
@aw285-unikent the above PR is on test - would you like us to roll out to live on tuesday 24th?

**Comment by aw285-unikent** [comment]
@eg270-unikent yes please

**Comment by eg270-unikent** [comment]
@aw285-unikent the pull request was rolled to live on Tues 24th February. I've checked and can view some courses such as http://www.kent.ac.uk/courses/undergraduate/2016/47/applied-psychology - can this issue be closed?

**Comment by aw285-unikent** [comment]
Yes thank you

Angela
