### ISSUE TITLE
Investigate design for displaying location on courses pages

### ISSUE THREAD

**Issue by eg270-unikent** [unikent/of-course#688]
As EMS,

I want to display the campus location more prominently on the courses pages

so that it is clearer where the course is taught

- Course Titles will no longer have location field present e.g. 'Comparative Literature (Canterbury and Paris) - MA' will become 'Comparative Literature - MA
- Location field is already populated in key facts but EMS would like this more prominent (underneath title/superscript etc.)

Assigning @jt353-unikent

**Comment by jt353-unikent** [comment]
Hi  @aw285-unikent  @eg270-unikent 

Here are some simple designs to include the location name. 
If the location includes a European centre, we could perhaps highlight it somehow to promote your European connection?

Thanks
Jonathan

![location-course-euro](https://cloud.githubusercontent.com/assets/4367005/7628998/fd6532a0-fa20-11e4-83d9-24dd1a05b3f2.jpg)
![location-course](https://cloud.githubusercontent.com/assets/4367005/7628997/fd6513d8-fa20-11e4-8818-c83ec2154231.jpg)

**Comment by aw285-unikent** [comment]
Hi @jt353-unikent @eg270-unikent many thanks for this. Please could we go with the second version for now (just the location names)? Many thanks, Angela

**Comment by aw285-unikent** [comment]
@eg270-unikent @jt353-unikent 

Just a reminder that we'll need to apply these changes to the snippet too and look at the way the course summary snippet(s) display the location information. 

Paris are using a version of the summary snippet here 

http://www.kent.ac.uk/paris/

However on this version, users have to manually name each programme as it will appear on the list in a 'links' file - the titles don't output automatically.

I have said to Paris that they should change the names to eg 'Film - MA (Canterbury and Paris)', Film - MA (Paris), Film - MA (Canterbury)' (once our changes, as above, have been rolled live) because, this is probably going to be the best way to distinguish similar courses from a search/browse perspective and I don't see a better way forward unless you guys do?

I know Mary wants to remove the location from the title on the actual location pages, so that users don't think it's part of the official degree title but she did say she was less concerned about this from a search perspective. 

On our quick search (within courses) perhaps we could output each programme as eg Film - MA (Canterbury and Paris) etc. The Canterbury and Paris could be in italics or different colour etc to make it look separate to the degree title but see what you think? 

Copying in Fritha for info regarding the Paris page which she helps edit @frithassell

**Comment by cs462-unikent** [comment]
Todo:

- [ ] Apply new design to of course
- [ ] Apply design to xcri snippet
- [ ] Find solution for quick search

**Comment by eg270-unikent** [comment]
@aw285-unikent we have rolled out the change to incorporate location as per Jonathan's design.

The quick search needs more thought and a bit more investigation. It looks like it's going to be a bigger piece of work than BAU so we'll need to figure out which sprint this can be scheduled into.

**Comment by eg270-unikent** [comment]
See #687 which incorporates the quicksearch. Closing this issue.
