### ISSUE TITLE
Prepare for 2016 PG prospectus launch

### ISSUE THREAD

**Issue by eg270-unikent** [unikent/of-course#742]
As EMS,

I want to be launch the PG prospectus on w/c 14th September

so that the 2016 programmes can be advertised

- [x] rollover prospectus in progs plant
- [x] put at /courses/postgraduate/2016 (before launch)
- ~~[ ] .htaccess so only staff can view (before launch)~~

@aw285-unikent can you confirm that we can remove the 2015 PG prospectus?

**Comment by jna-unikent** [comment]
Hi @aw285-unikent 

Please feel free to start publishing the PG 2016 programmes to live as and when they are ready. They should start appearing on the 2016 search page. E.g. on www-test: http://www-test.kent.ac.uk/courses/postgraduate/2016/search. This would allow you to test that the fees, modules etc. are being pulled in as expect. 

We don't think there is a need to protect those pages since there'll be no way of getting to them without knowing the url to them.

Do let us know if you come across any issues.

Thanks

Justice

**Comment by eg270-unikent** [comment]
Hi @aw285-unikent you should be good to go when you're ready to put the PG prospectus live. Published courses such as http://www.kent.ac.uk/courses/postgraduate/2016/1/actuarial-science are already live, but once you change the years over to 2016 the banner about the course being for an upcoming academic year should disappear.

Let me know if you have any issues

**Comment by aw285-unikent** [comment]
@eg270-unikent thanks for making the changeover. I've changed the front- and backend years to 2016 in the programmes plant and all looks to be OK. Many thanks
